apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: phoenix-db
  namespace: database
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:15.4
  storage:
    storageClass: standard
    size: 1Gi
  superuserSecret:
    name: postgres-superuser-secret
  bootstrap:
    initdb:
      database: phoenixdb
      owner: phoenix
      secret:
        name: phoenix-user-secret

