apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: database
  namespace: flux-system
spec:
  interval: 5m
  path: ./infra/database
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: database
  timeout: 2m
  wait: true

